"""baseline schema

Revision ID: f9d931baade6
Revises: 
Create Date: 2026-07-05 02:45:53.039292

"""
from __future__ import annotations

import pgvector.sqlalchemy
import sqlalchemy as sa
import sqlmodel  # noqa: F401 — SQLModel str columns render as sqlmodel.sql.sqltypes.AutoString
from sqlalchemy.dialects import postgresql

from alembic import op

revision = 'f9d931baade6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # research_task.embedding is a pgvector column — the extension must exist
    # before the table. Idempotent, and deliberately NOT dropped in downgrade
    # (other objects in the database may share it).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_event_created_at'), 'agent_event', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_event_task_id'), 'agent_event', ['task_id'], unique=False)
    op.create_table('api_key',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_key_hash'), 'api_key', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_key_user_id'), 'api_key', ['user_id'], unique=False)
    op.create_table('research_task',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sub_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('final_report', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_task_status'), 'research_task', ['status'], unique=False)
    op.create_index(op.f('ix_research_task_user_id'), 'research_task', ['user_id'], unique=False)
    op.create_table('telegram_bot_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bot_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('telegram_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        op.f('ix_telegram_bot_config_user_id'), 'telegram_bot_config', ['user_id'], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_bot_config_user_id'), table_name='telegram_bot_config')
    op.drop_table('telegram_bot_config')
    op.drop_index(op.f('ix_research_task_user_id'), table_name='research_task')
    op.drop_index(op.f('ix_research_task_status'), table_name='research_task')
    op.drop_table('research_task')
    op.drop_index(op.f('ix_api_key_user_id'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_key_hash'), table_name='api_key')
    op.drop_table('api_key')
    op.drop_index(op.f('ix_agent_event_task_id'), table_name='agent_event')
    op.drop_index(op.f('ix_agent_event_created_at'), table_name='agent_event')
    op.drop_table('agent_event')
    # ### end Alembic commands ###
